FROM public.ecr.aws/lambda/nodejs:14

# ENV CODEFRESH_API_KEY
# ENV WEBHOOK_SECRETS
# ENV JIRA_APPROVE_STATES
# ENV JIRA_DENY_STATES
ENV JIRA_EVENT_TYPES='issue_moved'
ENV JIRA_RESOLVE_FIELDS='false'
# ENV JIRA_CUSTOM_FIELD
ENV CODEFRESH_BASE_URL='g.codefresh.io'
ENV CODEFRESH_PORT='443'
ENV JIRA_PORT='443'
ENV DEBUG='false'
ENV TRIM_INPUT='true'
ENV CASE_SENSITIVE='false'

WORKDIR ${LAMBDA_TASK_ROOT}

COPY app.js package.json ${LAMBDA_TASK_ROOT}
RUN npm install

CMD ["app.handler"]
